fix: Incorrect chart values for user, group and memory limit
SchwarzIT/node-red-chart pull request #344
Opened 2024-08-13 07:55 UTC by gianmarco-mameli

Closes #343 

Fixed chart values for user, group and memory limit

2024-08-13 17:28 UTC, dirien requested changes
Hey @gianmarco-mameli,

Thanks for the PR. Could you revert the runAsUser/Group values and we are good to go to merge.

2024-08-13 17:29 UTC, dirien requested changes

2024-08-13 17:29 UTC, dirien commented on charts/node-red/Chart.yaml
> +    - Incorrect chart values for user, group and memory limit
```suggestion
    - Incorrect chart values for memory limit
```

2024-08-13 17:33 UTC, gianmarco-mameli commented on charts/node-red/values.yaml
> +  runAsGroup: 1000
Hi @dirien if you leave 10003 as user nodered raise an error when trying to do some operations, like clone a project. 
In my case the pod only works correctly with 1000 for uids.
If you want I can replicate the error and send you the pod log, in the meantime we can leave on hold the PR

Thanks

2024-08-13 19:56 UTC, gianmarco-mameli commented on charts/node-red/values.yaml
> +  runAsGroup: 1000
As example: I'm unable to use git clone function to download the project that I need to run on node red
```
Cloning into 'k3stest'...
No user exists for uid 10003
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Maybe I can investigate more and send the PR like you suggested, let me know

2024-08-30 12:58 UTC, gianmarco-mameli commented on charts/node-red/values.yaml
> +  runAsGroup: 1000
Hi @dirien, I've performed some tests and I get the same error, even trying to use 10000 as group and user.
The git clone inside the pod returns me
```
Cloning into '/data/projects/k3stest'...
    No user exists for uid 10000
```
Also similar problems are present in certain operation in nodered
No problem if I set 1000 as user.
Better to merge the pr without the mods on uid and gid, and maybe when I have a little more time I can check if there's a solution to use the chart with ids over 10000, in that case It's a problem confined in my environment

Thanks

2024-09-27 15:26 UTC, dirien commented
hi @gianmarco-mameli,

can you please run `git commit --amend --signoff` to approve the DCO please?

2024-09-27 15:38 UTC, gianmarco-mameli commented
Hi @dirien, no problem, I'm trying to solve the action on DCO but seems that your command, and the commands suggested from the DCO aren't working.
Tell me if I'm doing something wrong, thanks

2024-09-27 15:41 UTC, dirien commented
@gianmarco-mameli 

I would say now rebase the main branch into this branch, then `git commit --amend --signoff` and then `git push origin HEAD --force` it. This should fix this.

2024-09-27 15:59 UTC, gianmarco-mameli commented
I think it's still blocked, sorry for this mess

2024-09-28 08:11 UTC, dirien commented
@gianmarco-mameli Fixed it.

2024-09-28 08:12 UTC, merged